import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../scss/globals.scss';
import styles from '../scss/layout.module.scss';
import { Header, NavSidebar, Footer } from '../components';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.className} ${styles.body}`}>
        <div>
          <Header />
          <main className={styles.mainContainer}>
            <NavSidebar />
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
